version: '2'
services:
  node:
    build: .
    ports:
     - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
  mongo:
    image: "mongo:3.4.2"
    volumes:
     - ${HOME}/data/mongodb:/data/db
